In [1]:
import gecko
from pathlib import Path
import importlib
import gecko.plugins.dalton.loader as dalton_loader
import gecko.plugins.dalton.detect as dalton_detect
import gecko.core.load as core_load
import gecko.index as gecko_index
importlib.reload(dalton_loader)
importlib.reload(dalton_detect)
importlib.reload(core_load)
importlib.reload(gecko_index)
importlib.reload(gecko)

In [2]:
N2_DALTON_FILENAME = Path("../tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n2/dipole/quad_n2-aug-cc-pVDZ.out")
calc=gecko.load_calc(N2_DALTON_FILENAME)
calc.molecule.geometry
print(calc.molecule.geometry)
print(calc.molecule.symbols)

[[-2.909981  3.151719  0.      ]
 [-2.1458    0.698174  0.      ]
 [-1.709425  4.400491  0.      ]
 [-0.994638 -1.722408  0.      ]
 [ 0.068424  2.877395  0.      ]
 [ 1.008807  0.656265  0.      ]
 [-1.13142   1.116109  0.      ]
 [-0.951325  2.472788  0.      ]
 [-0.079865 -1.128099  0.      ]
 [ 0.        0.223821  0.      ]
 [-1.934119  3.417144  0.      ]
 [ 1.122651 -1.944425  0.      ]
 [ 0.941048 -3.168973  0.      ]
 [ 2.22627  -1.390826  0.      ]]
['H' 'H' 'H' 'H' 'H' 'H' 'C' 'C' 'C' 'C' 'N' 'N' 'O' 'O']

In [3]:
N2_MADNESS_FILENAME = Path("../tests/fixtures/calc_nlo_beta/NLO/madness/n2/output.json")
calc2=gecko.load_calc(N2_MADNESS_FILENAME)
print(calc2.molecule.geometry)
print(calc2.molecule.symbols)

[[-2.909981  3.151719  0.      ]
 [-2.1458    0.698174  0.      ]
 [-1.709425  4.400491  0.      ]
 [-0.994638 -1.722408  0.      ]
 [ 0.068424  2.877395  0.      ]
 [ 1.008807  0.656265  0.      ]
 [-1.13142   1.116109  0.      ]
 [-0.951325  2.472788  0.      ]
 [-0.079865 -1.128099  0.      ]
 [ 0.        0.223821  0.      ]
 [-1.934119  3.417144  0.      ]
 [ 1.122651 -1.944425  0.      ]
 [ 0.941048 -3.168973  0.      ]
 [ 2.22627  -1.390826  0.      ]]
['H' 'H' 'H' 'H' 'H' 'H' 'C' 'C' 'C' 'C' 'N' 'N' 'O' 'O']

In [4]:
import qcelemental.models.molecule as molecule

print(calc.molecule.get_hash())
print(calc2.molecule.get_hash())

molecule.Molecule.copy(calc.molecule)

bf45daf712d454b33534fa71ed5e8a070f7d0472
bf45daf712d454b33534fa71ed5e8a070f7d0472

'Install nglview for interactive visualization.'

"Molecule(name='C4H6N2O2', formula='C4H6N2O2', hash='bf45daf')"

In [5]:
from gecko.core.iterators import iter_calc_dirs
from gecko.recipes.shg_csv import build_beta_table
NLO_DIRECTORY= Path("../tests/fixtures/calc_nlo_beta/NLO")
dirs = list(iter_calc_dirs(NLO_DIRECTORY))
df = build_beta_table(dirs, require_geometry=False, verbose=True)
df

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n6/excited-state:excited-hf_n6-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n6/excited-state:excited-hf_n6-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n6/excited-state:excited-hf_n6-d-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n6/excited-state:excited-hf_n6-d-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n6/excited-state:excited-hf_n6-d-aug-cc-pVTZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n3/excited-state:excited-hf_n3-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n3/excited-state:excited-hf_n3-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n3/excited-state:excited-hf_n3-d-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n3/excited-state:excited-hf_n3-d-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n3/excited-state:excited-hf_n3-d-aug-cc-pVTZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n4/excited-state:excited-hf_n4-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n4/excited-state:excited-hf_n4-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n4/excited-state:excited-hf_n4-d-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n4/excited-state:excited-hf_n4-d-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n4/excited-state:excited-hf_n4-d-aug-cc-pVTZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n2/excited-state:excited-hf_n2-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n2/excited-state:excited-hf_n2-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n2/excited-state:excited-hf_n2-d-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n2/excited-state:excited-hf_n2-d-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n2/excited-state:excited-hf_n2-d-aug-cc-pVTZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n7/excited-state:excited-hf_n7-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n5/excited-state:excited-hf_n5-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n5/excited-state:excited-hf_n5-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n5/excited-state:excited-hf_n5-d-aug-cc-pVDZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n5/excited-state:excited-hf_n5-d-aug-cc-pVQZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

[gecko] FAILED to process calculation:
  path: /home/ahurtado/Projects/gecko/tests/fixtures/calc_nlo_beta/NLO/dalton/hf/n5/excited-state:excited-hf_n5-d-aug-cc-pVTZ.out
  error: ValueError: No 'Molecular geometry (au)' header found.

,calc_id,geom_id,mol_id,molecule_id,label,code,root,basis,method,omegaA,omegaB,omegaC,ijk,value
0,calc_45b53ce42cea5d37,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,C18H20N2O2,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,n9,madness,/home/ahurtado/Projects/gecko/tests/fixtures/c...,MRA,None,-0.0,0.0,0.0,xxx,20367.511065
1,calc_45b53ce42cea5d37,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,C18H20N2O2,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,n9,madness,/home/ahurtado/Projects/gecko/tests/fixtures/c...,MRA,None,-0.0,0.0,0.0,xxy,20978.973039
2,calc_45b53ce42cea5d37,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,C18H20N2O2,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,n9,madness,/home/ahurtado/Projects/gecko/tests/fixtures/c...,MRA,None,-0.0,0.0,0.0,xxz,-0.000933
3,calc_45b53ce42cea5d37,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,C18H20N2O2,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,n9,madness,/home/ahurtado/Projects/gecko/tests/fixtures/c...,MRA,None,-0.0,0.0,0.0,xyx,20978.973039
4,calc_45b53ce42cea5d37,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,C18H20N2O2,d58b7c5784de8a8905f01896b4c85d5d5bc6627a,n9,madness,/home/ahurtado/Projects/gecko/tests/fixtures/c...,MRA,None,-0.0,0.0,0.0,xyy,20305.120347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5440,calc_917ee439cca4126e,4f174627b142adf185aa2755d84443fa836ec02a,C20H22N2O2,4f174627b142adf185aa2755d84443fa836ec02a,quad_n10,dalton,/home/ahurtado/Projects/gecko/tests/fixtures/c...,d-aug-cc-pVTZ,None,-0.0,0.0,0.0,zyx,-0.000000
5441,calc_917ee439cca4126e,4f174627b142adf185aa2755d84443fa836ec02a,C20H22N2O2,4f174627b142adf185aa2755d84443fa836ec02a,quad_n10,dalton,/home/ahurtado/Projects/gecko/tests/fixtures/c...,d-aug-cc-pVTZ,None,-0.0,0.0,0.0,zyy,0.000000
5442,calc_917ee439cca4126e,4f174627b142adf185aa2755d84443fa836ec02a,C20H22N2O2,4f174627b142adf185aa2755d84443fa836ec02a,quad_n10,dalton,/home/ahurtado/Projects/gecko/tests/fixtures/c...,d-aug-cc-pVTZ,None,-0.0,0.0,0.0,zzx,13.790875
5443,calc_917ee439cca4126e,4f174627b142adf185aa2755d84443fa836ec02a,C20H22N2O2,4f174627b142adf185aa2755d84443fa836ec02a,quad_n10,dalton,/home/ahurtado/Projects/gecko/tests/fixtures/c...,d-aug-cc-pVTZ,None,-0.0,0.0,0.0,zzy,-37.011037
5444,calc_917ee439cca4126e,4f174627b142adf185aa2755d84443fa836ec02a,C20H22N2O2,4f174627b142adf185aa2755d84443fa836ec02a,quad_n10,dalton,/home/ahurtado/Projects/gecko/tests/fixtures/c...,d-aug-cc-pVTZ,None,-0.0,0.0,0.0,zzz,0.000000

In [8]:
df["code"].value_counts()
print(df.molecule_id.unique())
print(df.mol_id.unique())

['d58b7c5784de8a8905f01896b4c85d5d5bc6627a'
 'd53167f2c628236a06aa3c889afb0b0433670dcf'
 '83c240c57a5168e3d3871b5c943144601d240b58'
 'b41592909bfe2a5cc9877c8e0f40d0e6365c4bb8'
 '21503e2e3043b3e4d423b6950d4274311f788073'
 '140fcfeeb06902bd1955afe472655f66ed1688a3'
 '52db191a66fd94eb6fdea559060a02dc90aa06eb'
 'df0be70e1f76f66c8b0c9a30d5133037689687ee'
 'fda3b1242d1f44c14a809570c5a112468e55af63'
 'bf45daf712d454b33534fa71ed5e8a070f7d0472'
 'b9957eb0b5184466cf8ff935b03d5e0dcc983fb2'
 '0b177164aa57fa8bb70dd0df125fed5e850ba8c0'
 '6966ce4cc8fe5d65bc0bdc71cf9f01079a84b3f0'
 '9e5590eeade10eca49ce78aa8acf8d78f57bf280'
 '4f174627b142adf185aa2755d84443fa836ec02a']
['C18H20N2O2' 'C22H24N2O2' 'C32H34N2O2' 'C12H14N2O2' 'C6H8N2O2'
 'C30H32N2O2' 'C28H30N2O2' 'C24H26N2O2' 'C8H10N2O2' 'C4H6N2O2'
 'C26H28N2O2' 'C16H18N2O2' 'C14H16N2O2' 'C10H12N2O2' 'C20H22N2O2']

## Converting data into format for the beta 3D application

Fields are:
ijk,Afreq,Bfreq,Cfreq,molecule,Beta,basis,omega 

where molecule is just the formula, and omega is a frequency shorthand where since we care about shg, we take the sum -(omegaB+omegaC)=omegaA and only take values where omegaB=omegaC.  So basically, we filter frequencies from omegaB and omegaC to keep only the cases where omegaB=omegaC and number the unique pairs starting with 0,0,0=1 (-(omega1+omega1),omega1,omega1)=2 ...

In [ ]:
shg_df=df.copy()
shg_df=shg_df[["ijk","omegaA","omegaB","omegaC","mol_id","value",'basis']]
renames={"value":"Beta",'omegaA':'Afreq','omegaB':'Bfreq','omegaC':'Cfreq','mol_id':'molecule'}
shg_df.rename(columns=renames, inplace=True)

# for every molecule, filter rows where omegaB==omegaC, and create a new column 'omega' that numbers the unique pairs starting from 1

shg_df['omega'] = None
for mol in shg_df['molecule'].unique():
    mol_df = shg_df[shg_df['molecule'] == mol]
    filtered = mol_df[mol_df['Bfreq'] == mol_df['Cfreq']]
    unique_freqs = filtered['Bfreq'].unique()
    freq_mapping = {freq: idx + 0 for idx, freq in enumerate(sorted(unique_freqs))}
    shg_df.loc[filtered.index, 'omega'] = filtered['Bfreq'].map(freq_mapping)


shg_df = shg_df.dropna(subset=["omega"])

In [27]:
shg_df

      ijk  Afreq  Bfreq  Cfreq    molecule          Beta          basis omega
0     xxx   -0.0    0.0    0.0  C18H20N2O2  20367.511065            MRA     0
1     xxy   -0.0    0.0    0.0  C18H20N2O2  20978.973039            MRA     0
2     xxz   -0.0    0.0    0.0  C18H20N2O2     -0.000933            MRA     0
3     xyx   -0.0    0.0    0.0  C18H20N2O2  20978.973039            MRA     0
4     xyy   -0.0    0.0    0.0  C18H20N2O2  20305.120347            MRA     0
...   ...    ...    ...    ...         ...           ...            ...   ...
5440  zyx   -0.0    0.0    0.0  C20H22N2O2     -0.000000  d-aug-cc-pVTZ     0
5441  zyy   -0.0    0.0    0.0  C20H22N2O2      0.000000  d-aug-cc-pVTZ     0
5442  zzx   -0.0    0.0    0.0  C20H22N2O2     13.790875  d-aug-cc-pVTZ     0
5443  zzy   -0.0    0.0    0.0  C20H22N2O2    -37.011037  d-aug-cc-pVTZ     0
5444  zzz   -0.0    0.0    0.0  C20H22N2O2      0.000000  d-aug-cc-pVTZ     0

[2601 rows x 8 columns]